services:
  app:
    build:
      dockerfile: ./Dockerfile
    command: 
      - gunicorn
      - massaz72.wsgi:application
      - --bind
      - "0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./massaz72/media:/app/media
    restart: always
    env_file:
        - .env
    logging:
        driver: "json-file"
        options:
          max-file: "10"
          max-size: "200k"

