# Generated by Django 5.1.6 on 2025-03-23 06:38

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='experience',
        ),
        migrations.AddField(
            model_name='about',
            name='start_date',
            field=models.DateField(blank=True, help_text='Укажите дату начала работы массажистом', null=True, verbose_name='Дата начала работы'),
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(blank=True, help_text='Опишите опыт, специализацию и подход к работе', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='about',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Отметьте, если массажист активно принимает клиентов', verbose_name='Активный массажист'),
        ),
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(help_text='Введите полное имя массажиста', max_length=100, verbose_name='Имя массажиста'),
        ),
        migrations.AlterField(
            model_name='about',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Укажите порядок отображения на сайте (чем меньше число, тем выше в списке)', verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='about',
            name='photo',
            field=models.ImageField(blank=True, help_text='Загрузите профессиональное фото массажиста', upload_to='about/', validators=[main.models.validate_file_size], verbose_name='Фото массажиста'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.ImageField(upload_to='certificates/', validators=[main.models.validate_file_size], verbose_name='Изображение сертификата'),
        ),
    ]
