# Generated by Django 5.1.6 on 2025-03-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_about_experience_about_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
    ]
