# Generated by Django 5.1.6 on 2025-03-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_certificate_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_title', models.CharField(default='Услуги массажа', max_length=100, verbose_name='Head Title')),
                ('main_title', models.CharField(default='Твой массажист', max_length=100, verbose_name='Главный заголовок')),
                ('child_massage_title', models.CharField(default='Детский массаж', max_length=100, verbose_name='Детский массаж')),
                ('massage_title', models.CharField(default='Массаж', max_length=100, verbose_name='Массаж')),
                ('about_title', models.CharField(default='Обо мне', max_length=100, verbose_name='Обо мне')),
                ('contact_title', models.CharField(default='Контакты', max_length=50, verbose_name='Контакты')),
                ('career_start_year', models.PositiveIntegerField(default=2021, verbose_name='Год начала практики массажа')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
            },
        ),
    ]
