# Generated by Django 5.1.6 on 2025-03-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sitesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Настройки сайта', 'verbose_name_plural': 'Настройки сайта'},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='background',
            field=models.ImageField(default=0, upload_to='banners/', verbose_name='Фоновое изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='main_subtitle',
            field=models.CharField(default='Специалист по массажу', max_length=100, verbose_name='Главный подзаголовок'),
        ),
    ]
