# Generated by Django 5.1.6 on 2025-03-29 10:47

import massaz72.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_sitesettings_options_sitesettings_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='photo',
            field=models.ImageField(blank=True, help_text='Загрузите профессиональное фото массажиста', upload_to=massaz72.utils.get_file_path, validators=[massaz72.utils.validate_file_size], verbose_name='Фото массажиста'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.ImageField(upload_to=massaz72.utils.get_file_path, validators=[massaz72.utils.validate_file_size], verbose_name='Изображение сертификата'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='background',
            field=models.ImageField(upload_to=massaz72.utils.get_file_path, validators=[massaz72.utils.validate_file_size], verbose_name='Фоновое изображение'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='main_subtitle',
            field=models.CharField(default='Забота о Вашем здоровье', max_length=100, verbose_name='Главный подзаголовок'),
        ),
    ]
