# Generated by Django 5.1.6 on 2025-03-29 13:52

import massaz72.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_about_photo_alter_certificate_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to=massaz72.utils.get_file_path, validators=[massaz72.utils.validate_file_size], verbose_name='Фоновое изображение'),
        ),
    ]
