# Generated by Django 5.1.6 on 2025-07-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_sitesettings_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description',
            field=models.CharField(default='✅ Детский и женский массаж в Тюмени. Безопасно для детей, расслабляющие процедуры для женщин. Онлайн-запись. Выезд на дом.', max_length=255, verbose_name='Описание страницы сайта'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_keywords',
            field=models.CharField(default='массаж Тюмень, детский массаж, женский массаж, массаж для детей, массаж для женщин, массаж в Тюмени, онлайн запись, Массаж72, детский массаж Тюмень, женский массаж Тюмень, Тюмень массаж'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='head_title',
            field=models.CharField(default='Детский массаж в Тюмени | Женский массаж', max_length=100, verbose_name='Head Title'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='main_subtitle',
            field=models.CharField(default='Твой массажист - забота о Вашем здоровье', max_length=100, verbose_name='Главный подзаголовок'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='main_title',
            field=models.CharField(default='Детский и женский массаж в Тюмени', max_length=100, verbose_name='Главный заголовок'),
        ),
    ]
