# Generated by Django 5.2 on 2026-03-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_sitesettings_meta_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="max_messanger",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="MAX Messenger (номер или ссылка)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="telegram_username",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Telegram (username без @)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="whatsapp_number",
            field=models.CharField(
                blank=True,
                default="",
                max_length=20,
                verbose_name="WhatsApp (номер с кодом страны, без +)",
            ),
        ),
    ]
