# Generated by Django 5.2 on 2026-03-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_move_contacts_to_about"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="meta_keywords",
            field=models.TextField(
                default="массаж Тюмень, детский массаж, женский массаж, массаж для детей, массаж для женщин, массаж в Тюмени, онлайн запись, Массаж72, детский массаж Тюмень, женский массаж Тюмень, Тюмень массаж",
                verbose_name="Ключевые слова для поисковых систем",
            ),
        ),
    ]
