# Generated by Django 5.2 on 2026-03-16 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_sitesettings_meta_keywords_textfield"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="career_start_year",
        ),
    ]
