# Generated by Django 5.1.6 on 2026-05-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_career_start_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='max_messanger_active',
            field=models.BooleanField(default=True, verbose_name='MAX активен'),
        ),
        migrations.AddField(
            model_name='about',
            name='telegram_active',
            field=models.BooleanField(default=True, verbose_name='Telegram активен'),
        ),
        migrations.AddField(
            model_name='about',
            name='whatsapp_active',
            field=models.BooleanField(default=True, verbose_name='WhatsApp активен'),
        ),
        migrations.AlterField(
            model_name='about',
            name='max_messanger',
            field=models.CharField(blank=True, default='', help_text='Полная ссылка профиля из приложения MAX. Как получить: откройте MAX → Настройки → QR-код профиля → Поделиться → Скопировать ссылку. Ссылка выглядит так: https://max.ru/u/xxxxxxxx', max_length=255, verbose_name='MAX Messenger (ссылка профиля)'),
        ),
    ]
