# Generated by Django 5.1.6 on 2026-06-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_about_max_messanger_active_about_telegram_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='price_change_date',
            field=models.DateField(blank=True, help_text='Дата, с которой новые цены массажей вступают в силу. До этой даты на сайте показывается плашка о предстоящем изменении, а в карточках — текущие цены. Оставьте пустым, если изменение цен не планируется.', null=True, verbose_name='Дата изменения цен'),
        ),
    ]
