# Generated by Django 5.1.6 on 2026-06-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_sitesettings_price_change_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_verification',
            field=models.CharField(blank=True, default='', help_text='Только значение content из HTML-тега (без самого тега). Search Console → ресурс с префиксом URL → способ «Тег HTML».', max_length=100, verbose_name='Код подтверждения Google Search Console'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='yandex_verification',
            field=models.CharField(blank=True, default='', help_text='Только значение content из мета-тега (без самого тега). Яндекс.Вебмастер → добавить сайт → способ «Мета-тег».', max_length=100, verbose_name='Код подтверждения Яндекс.Вебмастер'),
        ),
    ]
