# Generated by Django 5.1.6 on 2026-06-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('percentage', 'Процент (%)'), ('amount', 'Фиксированная сумма (₽)')], default='percentage', max_length=10, verbose_name='Тип скидки')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Размер скидки')),
                ('date_from', models.DateField(verbose_name='Дата начала')),
                ('date_to', models.DateField(verbose_name='Дата окончания')),
                ('description', models.CharField(blank=True, help_text='Оставьте пустым — текст сформируется автоматически', max_length=255, verbose_name='Текст баннера')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
                'ordering': ['-date_from'],
            },
        ),
    ]
