# Generated by Django 5.2 on 2026-06-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0009_discount_global_prices_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_travel',
            field=models.BooleanField(default=False, verbose_name='Выездной'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='break_between_travel_minutes',
            field=models.PositiveIntegerField(default=60, verbose_name='Перерыв между выездными массажами (мин)'),
        ),
    ]
