# Generated by Django 5.1.6 on 2026-06-08 10:33

import django.db.models.deletion
import tgbot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(help_text='Числовой ID. Узнать можно через бота @userinfobot.', unique=True, verbose_name='Telegram ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='Имя / комментарий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
            ],
            options={
                'verbose_name': 'Администратор бота',
                'verbose_name_plural': 'Администраторы бота',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, default='', help_text='Токен, выданный @BotFather.', max_length=200, verbose_name='Токен бота')),
                ('is_enabled', models.BooleanField(default=False, help_text='Если выключено — webhook не принимает обновления.', verbose_name='Бот включён')),
                ('mode', models.CharField(choices=[('polling', 'Polling (опрос Telegram)'), ('webhook', 'Webhook')], default='polling', help_text='Polling — отдельный процесс «manage.py runbot». Webhook — Telegram сам шлёт обновления на сайт.', max_length=10, verbose_name='Режим работы')),
                ('public_url', models.URLField(blank=True, default='', help_text='Напр. https://massaz72.ru — нужен только для режима webhook.', verbose_name='Публичный адрес сайта')),
                ('secret_path', models.CharField(default=tgbot.models.generate_secret, editable=False, max_length=64, verbose_name='Секретный путь webhook')),
                ('secret_token', models.CharField(default=tgbot.models.generate_secret, editable=False, max_length=64, verbose_name='Секретный токен webhook')),
                ('bot_username', models.CharField(blank=True, default='', editable=False, max_length=100, verbose_name='Имя бота (@)')),
                ('welcome_text', models.TextField(blank=True, default='👋 Здравствуйте! Это бот массажиста.\n\nНапишите, какой массаж вас интересует и удобное время — я передам сообщение массажисту, и он свяжется с вами.\n\nНажмите «💰 Услуги и цены», чтобы посмотреть прайс, или «📝 Записаться», чтобы оставить заявку.', verbose_name='Приветствие (/start)')),
                ('request_prompt', models.TextField(blank=True, default='Напишите, пожалуйста, одним сообщением:\n• какой массаж интересует;\n• желаемые дату и время;\n• как с вами связаться.\n\nЯ сразу передам заявку массажисту. 🌿', verbose_name='Подсказка при записи')),
            ],
            options={
                'verbose_name': 'Настройки Telegram-бота',
                'verbose_name_plural': 'Настройки Telegram-бота',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, default='', max_length=100, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Фамилия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Первое обращение')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
            ],
            options={
                'verbose_name': 'Клиент бота',
                'verbose_name_plural': 'Клиенты бота',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DialogMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'От клиента'), ('out', 'Ответ массажиста')], max_length=3, verbose_name='Направление')),
                ('text', models.TextField(blank=True, default='', verbose_name='Текст')),
                ('admin_telegram_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID ответившего администратора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tgbot.telegramuser', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Переписка',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminForward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_telegram_id', models.BigIntegerField()),
                ('admin_message_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwards', to='tgbot.telegramuser')),
            ],
            options={
                'verbose_name': 'Пересланное сообщение',
                'verbose_name_plural': 'Пересланные сообщения',
                'constraints': [models.UniqueConstraint(fields=('admin_telegram_id', 'admin_message_id'), name='unique_admin_message')],
            },
        ),
    ]
