# Generated by Django 5.1.6 on 2026-06-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_booking_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='Доставлено')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='Ошибок')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлена')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['-created_at'],
            },
        ),
    ]
