# Generated by Django 5.1.6 on 2026-06-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_broadcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='subject',
            field=models.CharField(blank=True, default='', help_text='Жирный заголовок над текстом. Можно оставить пустым.', max_length=200, verbose_name='Тема'),
        ),
    ]
