# Generated by Django 5.1.6 on 2025-03-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Massage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название массажа')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('duration', models.PositiveIntegerField(verbose_name='Продолжительность (в минутах)')),
                ('categore', models.CharField(blank=True, null=True, verbose_name='Категория')),
                ('image', models.ImageField(blank=True, null=True, upload_to='massage_images/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Массаж',
                'verbose_name_plural': 'Массажи',
            },
        ),
    ]
