# Generated by Django 5.1.6 on 2025-03-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_category_remove_massage_categore_massage_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='massage',
            options={'ordering': ['massage_type', 'order'], 'verbose_name': 'Массаж', 'verbose_name_plural': 'Массажи'},
        ),
        migrations.RemoveField(
            model_name='massage',
            name='duration',
        ),
        migrations.AddField(
            model_name='massage',
            name='duration_max',
            field=models.PositiveIntegerField(default=50, verbose_name='Максимальная продолжительность (в минутах)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='massage',
            name='duration_min',
            field=models.PositiveIntegerField(default=30, verbose_name='Минимальная продолжительность (в минутах)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='massage',
            name='massage_type',
            field=models.CharField(choices=[('adult', 'Взрослый'), ('child', 'Детский')], default='child', max_length=5, verbose_name='Тип массажа'),
        ),
        migrations.AddField(
            model_name='massage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Очередность'),
        ),
    ]
