# Generated by Django 5.1.6 on 2025-03-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_massage_options_remove_massage_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='massage',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL'),
        ),
    ]
