# Generated by Django 5.1.6 on 2025-03-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20250322_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='massage',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
    ]
