# Generated by Django 5.1.6 on 2025-03-29 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_category_image_alter_massage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massage',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
