# Generated by Django 5.2 on 2025-07-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0009_remove_massage_category_delete_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="massage",
            options={
                "ordering": ["-massage_type", "order"],
                "verbose_name": "Массаж",
                "verbose_name_plural": "Массажи",
            },
        ),
        migrations.AddField(
            model_name="massage",
            name="location",
            field=models.CharField(
                default="Тюмень", max_length=255, verbose_name="Место проведения"
            ),
            preserve_default=False,
        ),
    ]
