# Generated by Django 5.1.6 on 2026-06-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_massage_options_massage_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='massage',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Будущая цена. Вступит в силу автоматически после даты изменения цен, заданной в «Настройках сайта». До этой даты на сайте показывается текущая цена.', max_digits=10, null=True, verbose_name='Новая цена'),
        ),
    ]
